// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5SmwsI0P1706L1X9U3CPiSVf4l8F4W8',
    appId: '1:829658498819:android:5d1681eb4bd0547c4b0b36',
    messagingSenderId: '829658498819',
    projectId: 'coursesapp-29dcf',
    databaseURL: 'https://coursesapp-29dcf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursesapp-29dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92qNSandZSS5xd2aUtT4kWG1osoEnqhU',
    appId: '1:829658498819:ios:7667eecab9eeef744b0b36',
    messagingSenderId: '829658498819',
    projectId: 'coursesapp-29dcf',
    databaseURL: 'https://coursesapp-29dcf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursesapp-29dcf.appspot.com',
    iosClientId: '829658498819-ntgqk13lbag5mnftc5q0qg4nrthf88uo.apps.googleusercontent.com',
    iosBundleId: 'com.coursesapp.app',
  );
}
